# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c3f1a1199ba9e96fc90b5dc2cf3b60d9c255e5722f81f78f6233e98c03ff2312f0ad9a13ad3e7626279effb1df0469f9cc282a0bcfa2c9c4992872e293ae83b

test:
  secret_key_base: f9c47e81c991f0916f5908118b1664563dc82a86ee722d3cc69ab2fdf95b1d4c4b8bfd1f4ad9ffc07116f9ec74fa0f60cc7e931e8ba9f14eb7ccf3a0dbb0f445

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
